import type { Config } from 'tailwindcss'

export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#b2c8e8',
        'secondary-container': '#c9deff',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#733600',
        'tertiary-fixed': '#ffdcc7',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e5e8ee',
        'primary-fixed-dim': '#a1c9ff',
        'on-primary-container': '#afd1ff',
        'surface-container-highest': '#e0e3e8',
        'surface-tint': '#1261a3',
        'inverse-on-surface': '#eef1f6',
        'inverse-primary': '#a1c9ff',
        'tertiary-fixed-dim': '#ffb787',
        'error': '#ba1a1a',
        'primary-container': '#005a9c',
        'on-background': '#181c20',
        'on-primary-fixed': '#001c37',
        'on-secondary-fixed': '#041c35',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f9',
        'tertiary': '#6a3100',
        'on-surface': '#181c20',
        'secondary-fixed': '#d2e4ff',
        'surface-bright': '#f7f9ff',
        'on-primary': '#ffffff',
        'outline': '#727781',
        'on-tertiary-container': '#ffc29c',
        'on-primary-fixed-variant': '#00487f',
        'secondary': '#4b607b',
        'primary': '#004275',
        'surface-container': '#ebeef3',
        'on-secondary-fixed-variant': '#334862',
        'on-secondary-container': '#4d627e',
        'outline-variant': '#c1c7d2',
        'on-surface-variant': '#414750',
        'background': '#f7f9ff',
        'surface-dim': '#d7dadf',
        'on-error': '#ffffff',
        'surface-variant': '#e0e3e8',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#311300',
        'tertiary-container': '#8d4401',
        'on-error-container': '#93000a',
        'surface': '#f7f9ff',
        'inverse-surface': '#2d3135',
        'primary-fixed': '#d2e4ff',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.75rem',
        'full': '0.5rem',
      },
      fontFamily: {
        'headline': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['0.75rem', { lineHeight: '1.5', fontWeight: '600', letterSpacing: '0.05em' }],
        'body-lg': ['1rem', { lineHeight: '1.5', fontWeight: '400', letterSpacing: '0.01em' }],
      },
      spacing: {
        '20': '5rem',
      },
      animation: {
        'ambient-hover': 'ambient 300ms cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        ambient: {
          '0%': { boxShadow: '0 0 0 rgba(0, 66, 117, 0)' },
          '100%': { boxShadow: '0 20px 40px rgba(0, 66, 117, 0.06)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
} as Config
